version: '2'

services:
    nginx:
        build: ./nginx
        image: nginx_https
        ports:
          -  "443:443"
        volumes:
          -  ./nginx/certificate:/etc/certificate
        container_name: nginx_https
